export const USER_MESSAGE_PATTERNS = {
  LOGIN: 'USER_MESSAGE_PATTERNS.LOGIN',
  LOGIN_WITH_GOOGLE: 'USER_MESSAGE_PATTERNS.LOGIN_WITH_GOOGLE',
  REGISTER: 'USER_MESSAGE_PATTERNS.REGISTER',
  GET_USER: 'USER_MESSAGE_PATTERNS.GET_USER',
  UPDATE_USER: 'USER_MESSAGE_PATTERNS.UPDATE_USER',
  USER_RESET_PASSWORD: 'USER_MESSAGE_PATTERNS.USER_RESET_PASSWORD',
  USER_ACTIVE_ACCOUNT: 'USER_MESSAGE_PATTERNS.USER_ACTIVE_ACCOUNT',
  CHECK_EMAIL_EXISTS: 'USER_MESSAGE_PATTERNS.CHECK_EMAIL_EXISTS',
  CHECK_OTP: 'USER_MESSAGE_PATTERNS.CHECK_OTP',

  // PROFILE
  PROFILE: {
    LOGIN_WITH_PROFILE: 'USER_MESSAGE_PATTERNS.PROFILE.LOGIN_WITH_PROFILE',
    GET_ALL_PROFILE_BY_USER_ID:
      'USER_MESSAGE_PATTERNS.PROFILE.GET_ALL_PROFILE_BY_USER_ID',
    GET_PROFILE: 'USER_MESSAGE_PATTERNS.PROFILE.GET_PROFILE',
    CREATE_PROFILE: 'USER_MESSAGE_PATTERNS.PROFILE.CREATE_PROFILE',
    UPDATE_PROFILE: 'USER_MESSAGE_PATTERNS.PROFILE.UPDATE_PROFILE',
    DELETE_PROFILE: 'USER_MESSAGE_PATTERNS.PROFILE.DELETE_PROFILE',
  },
};

export const PAYMENT_SYSTEM_MESSAGE_PATTERN = {
  PAYMENT: {
    CREATE_PAYMENT: 'PAYMENT_SYSTEM_MESSAGE_PATTERN.PAYMENT.CREATE_PAYMENT',
    RESPONSE_THIRD_PARTY_PAYMENT:
      'PAYMENT_SYSTEM_MESSAGE_PATTERN.PAYMENT.RESPONSE_THIRD_PARTY_PAYMENT',
    GET_MY_PAYMENT: '',
  },
  PACKAGE: {
    CREATE_PACKAGE: 'PAYMENT_SYSTEM_MESSAGE_PATTERN.PACKAGE.CREATE_PACKAGE',
    UPDATE_PACKAGE:
      'PAYMENT_SYSTEM_MESSAGE_PATTERN.PAYMENT.PACKAGE.UPDATE_PACKAGE',
    LIST_PACKAGE: 'PAYMENT_SYSTEM_MESSAGE_PATTERN.PACKAGE.LIST_PACKAGE',
  },
};

export const MEDIAS_MESSAGE_PATTERN = {
  COMICS: {
    LIST_COMICS: 'MEDIAS_MESSAGE_PATTERN.COMICS.LIST_COMICS',
    GET_COMICS: 'MEDIAS_MESSAGE_PATTERN.COMICS.GET_COMICS',
  },
};
