export const USER_MESSAGE_PATTERNS = {
  LOGIN: 'USER.LOGIN',
  REGISTER: 'USER.REGISTER',
  GET_USER: 'USER.GET_USER',
  UPDATE_USER: 'USER.UPDATE_USER',
  USER_RESET_PASSWORD: 'USER.USER_RESET_PASSWORD',
  USER_ACTIVE_ACCOUNT: 'USER.USER_ACTIVE_ACCOUNT',
  // PROFILE
  PROFILE: {
    GET_ALL_PROFILE_BY_USER_ID: 'PROFILE.GET_ALL_PROFILE_BY_USER_ID',
    GET_PROFILE: 'PROFILE.GET_PROFILE',
    CREATE_PROFILE: 'PROFILE.CREATE_PROFILE',
    UPDATE_PROFILE: 'PROFILE.UPDATE_PROFILE',
    DELETE_PROFILE: 'PROFILE.DELETE_PROFILE',
  },
};
